[package]
name = "hell-rust"
version = "0.1.0"
authors = ["Fariz Rizaldy <farizrizaldy@outlook.co.id>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dev-dependencies]
wasm-bindgen-test = "0.2"

[dependencies]
wasm-bindgen = "0.2"
md5 = "0.6.1"

[profile.release]
opt-level = "z"
lto = true
